version: '3.8'

x-airflow-common: &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE_DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE_LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    # Reduzindo a concorrência para economizar CPU/RAM
    AIRFLOW__CORE__PARALLELISM: 2
    AIRFLOW__CORE__DAG_CONCURRENCY: 2
    GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/gcp-key.json
  volumes:
    - ./dags:/opt/airflow/dags
    - ./dbt_project:/opt/airflow/dbt_project
    - ./plugins:/opt/airflow/plugins
    - ./keys:/opt/airflow/keys
  user: "${AIRFLOW_UID:-50000}:0"
  deploy:
    resources:
      limits:
        memory: 1.5G # Limite bem rígido para o AirFlow não estourar
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRESS_USER: airflow
      POSTGRESS_PASSWORD: airflow
      POSTGRESS_DB: airflow
    volumes:
      - ./data_volumes/postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M #Pg aguenta bem com pouca RAM para metadados
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fall", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  aiflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: bash -c "airflow users create --username admin --firstname MVP --lastname Rio Viagens Onibus Analytics" --role Admin --email admin@example.com --password admin"

  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio
    ports:
      - "9047:9047"
      - "31010:31010"
    environment:
      # A MÁGICA DA ECONOMIA AQUI:
      # Força o Java a usar no máximo 1.5GB de Heap.
      # O Dremio vai reclamar que é pouco, mas para MVP funciona.
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Xms1024m -Xmx1536m -XX:MaxDirectMemorySize=512m
    volumes:
      - ./data_volumes/dremio_data:/opt/dremio/data
    restart: unless-stopped

networks:
  default:
    name: mvp_network